##############################################################
# Linux Makefile of FFE 
#    Original Makefile by Duncan Mac-Vicar (duncan@linuxfan.com)
#  
# Rick Leite (ric@asbyte.com.br)
# Claudemir P. da Luz Jr. <claudemir@virtuallink.com.b>

LIBS=alleg-4.0.3 alleg_unsharable almp3
INCLUDE=/usr/local/include
LOAD=/usr/X11R6/lib
EXEC=../kof2003
GH=config.h global.h macros.h defs.h
OBJS=batle.o display.o inits.o intro.o loads.o logger.o main.o palettes.o monitor.o moves.o mp3.o refresh.o screenshot.o startmenu.o initfiles.o wavsounds.o sprites.o effects.o options.o

CC=/usr/bin/gcc
#CFLAGS=-g -W -O3 -static
CFLAGS=-g -Wall -Werror -O6

include makefile.lnx
